core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url
from shootr.core import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^bundle/(?P<bundle_id>\d+)/', views.get_bundle, name='get_bundle')
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, handler404, handler500, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

handler404
handler500

urlpatterns = patterns('',
    url(r'^', include('shootr.core.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^admin/', include(admin.site.urls)),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

core/models.py
# -*- coding: utf-8 -*-
import os
import hashlib
import socket
from django.db import models
from settings import UPLOAD_DIR

class Bundle(models.Model):

    def __unicode__(self):
        return u'Bundle %d' % self.id


def upload_to(instance, filename):
    base_name, ext = os.path.splitext(filename)
    hash_name = hashlib.md5(base_name).hexdigest()
    name = '%s%s' % (hash_name, ext)
    return os.path.join(os.path.join(UPLOAD_DIR + str(instance.bundle.id)), name)


def thumbnail_upload_to(instance, filename):
    base_name, ext = os.path.splitext(filename)
    hash_name = hashlib.md5(base_name).hexdigest()
    name = '%s%s' % (hash_name, ext)
    base_path = os.path.join(str(instance.bundle.id), name)
    return os.path.join(os.path.join(UPLOAD_DIR + 'thumbs'), base_path)

class ScreenshotManager(models.Manager):

    def ready(self):
        return self.get_query_set().filter(image__isnull=False)

class Screenshot(models.Model):
    bundle = models.ForeignKey('core.Bundle')
    url = models.CharField(max_length=1024)
    title = models.TextField(null=True)
    image = models.ImageField(null=True, upload_to=upload_to)
    thumbnail = models.ImageField(null=True, upload_to=thumbnail_upload_to)
    scheduled = models.DateTimeField(auto_now_add=True)
    saved = models.DateTimeField(null=True)

    def __unicode__(self):
        return u'Screenshot of %s' % self.url
    

core/views.py
# -*- coding: utf-8 -*-
import urlparse
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django import forms
from shootr.core.models import Bundle, Screenshot
from shootr.core.tasks import make_screenshot


class ScreenshotForm(forms.Form):
    urls = forms.CharField(widget=forms.Textarea(attrs={'class': 'span12'}), label=u'Адреса сайтов', )

    def clean_urls(self):
        urls = [
                self.clean_single_url(url) for url in \
                self.cleaned_data['urls'].strip().split()
        ]
        return urls

    def clean_single_url(self, url):
        scheme, netloc, path, query, fragment = urlparse.urlsplit(url)
        if scheme != 'http':
            scheme = 'http'
        if not netloc:
            netloc, path = path, ''
        result = urlparse.urlunsplit((scheme, netloc, path, query, fragment))
        return result

    def save(self):
        bundle = Bundle.objects.create()
        for url in self.cleaned_data['urls']:
            shot = Screenshot.objects.create(bundle=bundle, url=url)
            make_screenshot.delay(shot)
        return bundle


def index(request):
    form = ScreenshotForm(request.POST or None)
    bundle_list = []
    bundle_no = 1
    bundle_key = 'bundle%d' % bundle_no
    while bundle_key in request.POST:
        bundle_list.append(Bundle.objects.get(id=request.POST.get(bundle_key)))
        bundle_no += 1
        bundle_key = 'bundle%d' % bundle_no
    if form.is_valid():
        bundle = form.save()
        bundle_list.append(bundle)
        form = ScreenshotForm()
    return render_to_response('core/index.html', {'form': form, 'bundle_list': bundle_list})


def get_bundle(request, bundle_id):
    bundle = get_object_or_404(Bundle, pk=bundle_id)
    return render_to_response('core/get_bundle.html', {'bundle': bundle})

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <link rel="stylesheet" href="/media/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/media/css/style.css" />
        {% block head %}{% endblock %}
    </head>
    <body>
    	<div class="container">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
							<li><a class="brand" href="/">Скриншоты сайтов</a></li>
						</ul>
					</div>
				</div>
			</div>
    		{% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/core/get_bundle.html
{% extends "base.html" %}

{% block head %}
	<script src="/media/fancybox/jquery.fancybox.pack.js"></script>
	<link rel="stylesheet" href="/media/fancybox/jquery.fancybox.css" />
	<script type="text/javascript">
		$(function(){
			$(".fancybox").fancybox();
	
			var undone = true;
			
	        var reload = function() {
	        	undone = Boolean($(".thumbnail > img").size());
	            $.get(".").success(function(data, status, deffered){
	                var new_thumbs = $('.thumbnails', data);
	                $('.thumbnails').replaceWith(new_thumbs);
	            });
	            if (undone)
	                setTimeout(reload, 1000);
	        };
	        
	        reload();
		});
	</script>
{% endblock %}

{% block content %}

<ul class="thumbnails">
	{% for shot in bundle.screenshot_set.all %}
        {% if shot.image %}
            <li class="span3">
                <div class="thumbnail">
                    <a href="/media/{{ shot.image }}" class="fancybox" rel="thumbnails">
                        <img src="/media/{{ shot.thumbnail }}" />
                    </a>
                    <strong>{{ shot.title|truncatewords:3 }}</strong><br />
                    {{ shot.url }}<br />
                    <em>Фотография сделана {{ shot.saved|date:"d F, H:i" }}</em>
                </div>
            </li>
        {% else %}
            <li class="span3"><div class="thumbnail">
                <img src="/media/img/loading.gif" />
                <strong>Ожидаем завершения загрузки</strong><br />
                Это пример блока загрузки<br />
                <em>Фотография еще не готова</em>
            </li>
        {% endif %}
	{% endfor %}

</ul>
{% endblock %}

templates/core/index.html
{% extends "base.html" %}

{% block head %}
	<script type="text/javascript">
		$(function(){
			$(".bundle").each(function() {
				var bundle_id = $(this).find(".bundle-id").html(),
					bundle = $(this);
				var check = function() {
					var bundle_url = "/bundle/" + bundle_id + "/ .thumbnails"
					bundle.find(".bundle-process").load(bundle_url);
					var loaded = Boolean(bundle.find(".thumbnail").size()),
						undone = Boolean(bundle.find(".thumbnail > img").size());
					if (!loaded || undone)
		                setTimeout(check, 1000);
					else {
						bundle.find(".bundle-status").html(
							'<div class="ready">' +
								'<a href="' + bundle_url + '" target="_blank">Результат</a>' +
							'</div>'
						);
					}
				};
				check();
			});
		});
	</script>
{% endblock %}

{% block content %}
	{% for bundle in bundle_list %}
		<div class="bundle">
			<div class="bundle-id">{{ bundle.id }}</div>
			<div class="bundle-process"></div>
			<div class="bundle-status">
	        	<div class="loading">
	        		Скриншотики делаются...
	        	</div>
			</div>
		</div>
	{% endfor %}
	<div class="alert alert-info">
		Привет. Я фотографирую сайты. Введи несколько адресов URL в поле, которое расположено ниже (по одному адресу
		в каждой строке), и получи высококачественные скриншоты сайтов, которые будут сохранены в моей базе данных
		навечно.
	</div>
	<form action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		{% for bundle in bundle_list %}
			<input type="hidden" name="bundle{{ forloop.counter }}" value="{{ bundle.id }}"/>
		{% endfor %}
		<button type="submit" class="btn-primary">Сфотографировать</button>
	</form>
{% endblock %}